# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
cities = pd.read_csv("../output_data/cities.csv")
cities.head()

,City,Latitude,Longitute,Max Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
0,Kapaa,22.0752,-159.3190,79.12,84,75,1.99,US,1627316442
1,Barrow,71.2906,-156.7887,39.22,99,90,9.22,US,1627316321
2,Vaini,-21.2000,-175.2000,71.76,100,75,5.75,TO,1627316443
3,Qaanaaq,77.4840,-69.3632,43.63,54,89,9.75,GL,1627316436
4,Saint Paul Harbor,57.7900,-152.4072,54.91,82,90,0.00,US,1627316446

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
gmaps.configure(api_key=g_key)

locations = cities [["Latitude", "Longitute"]]
humidity = cities["Humidity"].astype(float)       

fig = gmaps.figure()

heat_layer=gmaps.heatmap_layer(locations, weights = humidity, dissipating = False, max_intensity = 150, point_radius = 3)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [11]:
bestweather_df = cities.loc[(cities["Max Temperature"] < 85) & (cities["Max Temperature"] > 60) & (cities["Cloudiness"] == 0) & (cities["Humidity"] < 70), :]
bestweather_df = bestweather_df.dropna(how = "any")
bestweather_df.reset_index(inplace=True)
del bestweather_df['index']
bestweather_df.head()

,City,Latitude,Longitute,Max Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
0,Pisco,-13.7000,-76.2167,68.05,68,0,10.36,PE,1627316464
1,Kropotkin,45.4375,40.5756,83.82,35,0,11.59,RU,1627316499
2,East London,-33.0153,27.9116,63.54,55,0,6.91,ZA,1627316363
3,Cape Town,-33.9258,18.4232,68.41,59,0,8.05,ZA,1627316514
4,Arraial do Cabo,-22.9661,-42.0278,82.36,61,0,18.41,BR,1627316307

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [20]:
hotel_df = bestweather_df[["City","Country","Latitude","Longitute"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

                    City Country  Latitude  Longitute Hotel Name
0                  Pisco      PE  -13.7000   -76.2167
1              Kropotkin      RU   45.4375    40.5756
2            East London      ZA  -33.0153    27.9116
3              Cape Town      ZA  -33.9258    18.4232
4        Arraial do Cabo      BR  -22.9661   -42.0278
5   Vila Franca do Campo      PT   37.7167   -25.4333
6                 Taltal      CL  -25.4000   -70.4833
7              Dongsheng      CN   39.8161   109.9776
8         Port Elizabeth      ZA  -33.9180    25.5701
9      São João da Barra      BR  -21.6403   -41.0511
10              Misratah      LY   32.3754    15.0925
11             Izberbash      RU   42.5696    47.8645
12                  Vila      PT   42.0304    -8.1588
13              Benghazi      LY   32.1167    20.0667
14              Coquimbo      CL  -29.9533   -71.3436
15              Goderich      CA   43.7501   -81.7165
16                Zlobin      HR   45.2924    14.6541
17               Ashtian      IR   34.5217    50.0019
18               Rosetta      EG   31.4044    30.4164
19          Lappeenranta      FI   61.0587    28.1887

In [21]:
radius = 5000
types = "lodging"

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {"radius": radius, "type": types, "key":g_key}

for index, row in hotel_df.iterrows():
    location=row[["Latitude", "Longitute"]].values
    
    params["location"]= f'{location[0]},{location[1]}'
    
    query_url=requests.get(base_url, params=params).json()
    results = query_url['results']
    
    try:
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']
    except (KeyError, IndexError):
        print("There is a missing field. Moving past.....")

hotel_df=hotel_df[hotel_df["Hotel Name"]!= ""]
hotel_df

,City,Country,Latitude,Longitute,Hotel Name
0,Pisco,PE,-13.7000,-76.2167,Hotel San Isidro Oficial
1,Kropotkin,RU,45.4375,40.5756,Hotel Europe Kropotkin
2,East London,ZA,-33.0153,27.9116,Tu Casa
3,Cape Town,ZA,-33.9258,18.4232,Southern Sun Waterfront Cape Town
4,Arraial do Cabo,BR,-22.9661,-42.0278,Pousada Porto Praia
5,Vila Franca do Campo,PT,37.7167,-25.4333,Pestana Bahia Praia
6,Taltal,CL,-25.4000,-70.4833,Residencial Karime
7,Dongsheng,CN,39.8161,109.9776,Crowne Plaza Ordos
8,Port Elizabeth,ZA,-33.9180,25.5701,39 On Nile Guest House
9,São João da Barra,BR,-21.6403,-41.0511,Pousada Porto De Canoas
10,Misratah,LY,32.3754,15.0925,فندق الماسة
11,Izberbash,RU,42.5696,47.8645,Ramina
12,Vila,PT,42.0304,-8.1588,Hotel Castrum Villae by Walk Hotels
13,Benghazi,LY,32.1167,20.0667,Tibesti Hotel
14,Coquimbo,CL,-29.9533,-71.3436,Punto de encuentro
15,Goderich,CA,43.7501,-81.7165,Harmony Inn
16,Zlobin,HR,45.2924,14.6541,Hotel Bitoraj Fuzine
17,Ashtian,IR,34.5217,50.0019,بنیاد مسکن شهرستان آشتیان
18,Rosetta,EG,31.4044,30.4164,Green Valley
19,Lappeenranta,FI,61.0587,28.1887,Original Sokos Hotel Lappee

In [23]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitute"]]

In [24]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

# Display figure
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))